export const projects = [
  {
    category: "Web App",
    title: "Dacapo (Elerning from korea)",
    description:
      "Dacapo is an e-learning platform from Korea specifically designed for pilot learning. This application provides exam features, daily quizzes, and an interactive learning system. Dacapo supports four login methods, namely Google, Naver, Apple, and Kakao. In addition, integration with TossPayments allows users to make payments easily and securely.",
    stack: [
      { name: "Next js" },
      { name: "SCSS" },
      { name: "Typescript" },
      { name: "Firebase" },
      { name: "Tanstack Query" },
      { name: "Tiptap" },
      { name: "Antd" },
      { name: "Tosspayments" },
      { name: "Excalidraw" },
      { name: "Ckeditor" },
    ],
    image: "/assets/project/dacapo.png",
    demo: "https://flydacapo.com/",
  },
  {
    category: "Web App",
    title: "AviationHub – Aviation Information Hub",
    description:
      "AviationHub is a comprehensive aviation information hub that provides real-time data and insights about flights, airports, and aviation industry updates. sales ebooks, and aviation newsletter. The platform is designed to cater to aviation enthusiasts, professionals, and travelers seeking accurate and up-to-date information about the aviation sector.",
    stack: [
      { name: "Next.js" },
      { name: "Resend" },
      { name: "Prisma" },
      { name: "Supabase" },
      { name: "R2 Cloudflare" },
      { name: "TypeScript" },
      { name: "Tailwind CSS" },
      { name: "shadcn" },
      { name: "Axios" },
      { name: "TanStack Query" },
      { name: "Zod" },
    ],
    image: "/assets/project/avationhub.png",
    demo: "https://www.aviationhub.id/",
  },
  {
    category: "Web App",
    title: "Showroom Kita – Car Showroom themed with AI Assistant",
    description:
      "Our Showroom is a web-based car showroom application that provides detailed information on various vehicle models, specifications, and prices. The platform allows users to browse various car categories, view images, access comprehensive details, and use AI Assistant features to help make informed purchasing decisions. The application uses Google Sheets as a database to store and manage showroom and vehicle data.",
    stack: [
      { name: "Next.js" },
      { name: "Gemini AI Model" },
      { name: "Spreadsheet for Database" },
      { name: "R2 Cloudflare" },
      { name: "TypeScript" },
      { name: "Tailwind CSS" },
      { name: "shadcn" },
      { name: "Axios" },
      { name: "TanStack Query" },
    ],
    image: "/assets/project/showroom1.png",
    demo: "https://showroom-kita.vercel.app/",
  },
  {
    category: "Web App",
    title:
      "Showroom Kita – Car Showroom themed Luxury Dark Automotive and with price comparison and installment simulation features.",
    description:
      "Our Showroom is a web-based car showroom application that provides detailed information on various vehicle models, specifications, and prices. The platform allows users to browse various car categories, view images, access comprehensive details, and use AI Assistant features to help make informed purchasing decisions. The application uses Google Sheets as a database to store and manage showroom and vehicle data.",
    stack: [
      { name: "Next.js" },
      { name: "Gemini AI Model" },
      { name: "Spreadsheet for Database" },
      { name: "R2 Cloudflare" },
      { name: "TypeScript" },
      { name: "Tailwind CSS" },
      { name: "shadcn" },
      { name: "Axios" },
      { name: "TanStack Query" },
    ],
    image: "/assets/project/showroom2.png",
    demo: "https://showroom-kita-2.vercel.app/",
  },
  {
    category: "Web App",
    title:
      "Showroom Kita – Classic Clean Car Showroom with Price Comparison and Installment Simulation.",
    description:
      "Showroom Kita is a web-based car showroom application with a classic and clean design that provides detailed information about various vehicle models, specifications, and prices. Users can browse car categories, view vehicle images, compare prices, access complete vehicle details, and calculate installment simulations. The application uses Google Sheets as a database to store and manage showroom and vehicle data.",
    stack: [
      { name: "Next.js" },
      { name: "Spreadsheet for Database" },
      { name: "R2 Cloudflare" },
      { name: "TypeScript" },
      { name: "Tailwind CSS" },
      { name: "shadcn" },
      { name: "Axios" },
      { name: "TanStack Query" },
    ],
    image: "/assets/project/showroom3.png",
    demo: "https://showroom-kita-3.vercel.app/",
  },
  {
    category: "Web App",
    title: "SIPINTER – National ASN Assessment System",
    description:
      "SIPINTER is a national-scale web application designed to manage the Indonesian Civil Servant assessment process with high system complexity. The platform supports 11 distinct user roles, each with different permissions, responsibilities, and workflows. It handles end-to-end assessment processes including submission, multi-level verification, approval, rejection, and monitoring. The system features structured assessment pages, role-based dashboards, dynamic form validation, clear status indicators, controlled access based on roles, and data export functionality to ensure accuracy, transparency, and consistency in national ASN evaluations.",
    stack: [
      { name: "Astro" },
      { name: "React" },
      { name: "Golang" },
      { name: "TypeScript" },
      { name: "Tailwind CSS" },
      { name: "Axios" },
      { name: "TanStack Query" },
      { name: "Zod" },
    ],
    image: "/assets/project/sipinter-bkn.png",
  },
  {
    category: "Web App",
    title: "Hand Gesture Navigation using MediaPipe & Real-Time AI Detection",
    description:
      "This website is an interactive project that allows users to navigate pages using hand gestures in real-time, with the help of MediaPipe technology and AI to improve detection accuracy. Built using React, Next.js, and Tailwind CSS, and supported by GitHub Copilot Pro and a free domain from the GitHub Student Pack, this project aims to be a case study in the application of gesture recognition and human-computer interaction (HCI) on the modern web.",
    stack: [
      { name: "Next js" },
      { name: "Tailwind" },
      { name: "Typescript" },
      { name: "Zustand" },
      { name: "React Icons" },
      { name: "Mediapipe" },
    ],
    image: "/assets/project/hand-gestur.png",
    github: "https://github.com/ahmdriyo/navigation-hand-gesture-recognition",
  },
  {
    category: "Web App",
    title: "Admin Dashboard Rocket Deli",
    description:
      "Admin Dashboard Rocket Deli is a web-based administration system designed to manage a South Korean restaurant efficiently. It allows administrators to handle menu management, orders, transactions, and operational data through a structured and user-friendly dashboard to support daily restaurant operations.",
    stack: [
      { name: "Next js" },
      { name: "Tailwind" },
      { name: "Typescript" },
      { name: "Axios" },
      { name: "Tanstack" },
      { name: "Lucide React" },
      { name: "Zod" },
    ],
    image: "/assets/project/admin-dashboard.png",
  },

  {
    category: "Web App",
    title: "KapalIndo",
    description:
      "KapalIndo is a web application designed to provide comprehensive information about ships in Indonesia. This platform offers detailed data on various types of vessels, including passenger ships, cargo ships, and fishing boats. Users can access information such as ship specifications, ownership details, registration status, and operational history. KapalIndo serves as a valuable resource for maritime professionals, researchers, and anyone interested in the Indonesian shipping industry.",
    stack: [
      { name: "Astro JS" },
      { name: "React JS" },
      { name: "Vue JS" },
      { name: "Tailwind" },
      { name: "Typescript" },
    ],
    image: "/assets/project/kapalindo.png",
    demo: "https://kapalindo-nusantara.vercel.app",
  },
  {
    category: "Web App",
    title: "Sistem Pendukung Keputusan Pemilihan Perumahan Terbaik",
    description:
      "This project is a web-based application designed to assist users in determining the most ideal housing options based on several assessment criteria such as price, distance to the city center, amenities, and transportation access. The system utilizes the Simple Additive Weighting (SAW) method, a weighted summation method widely used in multi-criteria decision-making (MCDM).",
    stack: [
      { name: "Next js" },
      { name: "Tailwind" },
      { name: "Typescript" },
      { name: "Axios" },
      { name: "Mysql" },
      { name: "Radix UI" },
      { name: "Prisma" },
      { name: "Jspdf Autotable" },
    ],
    image: "/assets/project/spk-saw.png",
    github: "https://github.com/ahmdriyo/spk-saw-perumahan2",
  },
  {
    category: "Web App",
    title: "Sistem Informasi Transportasi Kalsel",
    description:
      "South Kalimantan Transportation Information System is a website that provides complete information about transportation in the South Kalimantan region. This application is equipped with a geographic map feature (GeoMap) that displays terminal locations, as well as interactive navigation using gesture recognition, allowing users to navigate pages with just hand movements in real-time.",
    stack: [
      { name: "Next js" },
      { name: "Tailwind" },
      { name: "Typescript" },
      { name: "Antd" },
      { name: "Supabase" },
      { name: "Mediapipe" },
      { name: "Prisma" },
      { name: "Leaflet" },
    ],
    image: "/assets/project/simt.png",
    github: "https://github.com/ahmdriyo/next-js-admin-template",
    demo: "https://sistem-informasi-transportasi.vercel.app/",
  },
  {
    category: "Web App",
    title: "Mahakreatif Studio",
    description:
      "Mahakreatif Studio is a freelance platform specifically for students, designed while participating in the Independent Campus Entrepreneurship (WMK) program. This website is a creative platform for students to offer digital services or projects, build portfolios, and connect with potential clients professionally and easily.",
    stack: [
      { name: "Next js" },
      { name: "Tailwind" },
      { name: "Typescript" },
      { name: "Mantine" },
      { name: "Supabase" },
      { name: "Prisma" },
      { name: "Tiptap" },
      { name: "Framer Motion" },
      { name: "Midtrans" },
    ],
    image: "/assets/project/Mahakreatif.png",
    github: "https://github.com/ahmdriyo/Fullstack-MahaKreatif",
    demo: "https://www.mahakreatif-studio.com/",
  },
  {
    category: "Web App",
    title: "Company Profile",
    description:
      "This company profile website was developed using Copilot Agent from GitHub, where 90% of the code was written by Ai from AI prompts in less than 1 hour. Manual adjustments were made to adjust the design and content. This website is open-source and free to be developed according to your needs.",
    stack: [
      { name: "Next js" },
      { name: "Tailwind" },
      { name: "Typescript" },
      { name: "Antd" },
      { name: "Framer Motion" },
    ],
    image: "/assets/project/company-profile.png",
    github: "https://github.com/ahmdriyo/company-profile",
    demo: "https://company-profile-dummy.vercel.app/",
  },
  {
    category: "Web App",
    title: "Website Trayek Angkutan Umum.",
    description:
      "Public Transportation Route Website is a web-based platform that provides route information for various types of public transportation. This website is designed to make it easier to see available transportation routes, especially in areas with many transportation options.",
    stack: [
      { name: "Html" },
      { name: "Css" },
      { name: "Javascript" },
      { name: "Tailwind" },
      { name: "Next Js" },
      { name: "Firebase" },
    ],
    image: "/assets/project/angkutan.png",
    github: "https://github.com/ahmdriyo/web-angkutan.git",
    demo: "https://web-angkutan.vercel.app/",
  },
  {
    category: "Web App",
    title: "Web GIS Kampus di Barito Kuala.",
    description:
      "Web GIS Campus in Barito Kuala is a website based on Geographic Information System (GIS) that displays details of campuses in the Barito Kuala area. This application is equipped with an interactive map that marks the location of each campus accurately using markers.",
    stack: [
      { name: "Html" },
      { name: "Css" },
      { name: "Javascript" },
      { name: "React Js" },
      { name: "Firebase" },
      { name: "Openstreetmap" },
      { name: "Leaflet" },
    ],
    image: "/assets/project/gis.png",
    github: "https://github.com/ahmdriyo/web_sig_baritokuala.git",
    demo: "https://web-gis-kampusbaritokuala.vercel.app/",
  },
  {
    category: "Web App",
    title: "Website Trayek Kereta.",
    description:
      "Train Track Website is an informative website that displays train routes or tracks. Users can see the train tracks visually and clearly, helping in planning a trip or simply recognizing the available train transportation network.",
    stack: [
      { name: "Html" },
      { name: "Css" },
      { name: "TypeScript" },
      { name: "Tailwind" },
      { name: "Next Js" },
      { name: "Firebase" },
    ],
    image: "/assets/project/kereta.png",
    github: "https://github.com/ahmdriyo/web-angkutan",
    demo: "https://web-kereta.vercel.app/",
  },
];
